### ISSUE TITLE
建议大家不要无脑喷

### ISSUE THREAD

**Issue by hgoldfish** [konjac/ulang-source-decompiled#1]
正如 kotlin 基于 jvm, typescript 基于 javascript一样。从源代码看，木兰也是一个存在于其它生态上的语言。同样有语法解析，把语法树“编译”成其它语言。只不过 kotlin/typescript 都是原本语言的超集。而木兰语言是一个基于 python 语法替换后的子集。比如把`true_value if condition else false_value`替换成`condiion?true_value:false_value`，看了一下源代码，貌似不支持类的定义，也不支持 with-statement 和 decorator 这些高级语法。

如果这真的是一个面向小孩子的编程语言。我觉得是可以说得通的。

因为语法简单，想扩展成支持嵌入式的语言也比较容易。

再给大家介绍一个基于 python 的玩具语言：

https://github.com/hgoldfish/gsion_script

**Comment by hgoldfish** [comment]
我又再仔细了解了一下。确实这就是一个 python 语法替换后的新语言。看来确定是骗人的了。

**Comment by nobodxbodon** [comment]
木兰重现项目开源在 gitee：https://gitee.com/MulanRevive/mulan-rework
